FROM monitor-template

ARG VERSION="dev"

LABEL Name="rest-server" Version="$VERSION"\
      Description="Alexander's Monitoring Server REST Server" \
      Maintainer="Alexander Tolkachev <alexander.e.tolkachev@gmail.com>"

USER monitoring-server

ENTRYPOINT monitor-rest