language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install git+https://github.com/ATolkachev/monitoring-service.git/#egg=monitor
script:
  - pytest tests/tests.py
services:
  - mongodb
  - rabbitmq
